name: CI

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: Lint (non-blocking)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          pip install ruff black

      - name: Ruff check
        run: ruff check .
        continue-on-error: true

      - name: Black check (non-blocking)
        run: black --check .
        continue-on-error: true

  test:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install pytest

      - name: Run tests (exclude live/integration by file selection)
        run: |
          pytest -q tests/test_config.py tests/test_db.py tests/test_models.py tests/test_parsers.py
